# The quick CI tests run on every push to a PR. They perform a quick check
# if the feature set and codebase are stable in general, but only for
# a representative selection of environments.
name: CI
on:
  pull_request:
    branches:
      - main
      - main2
      - release/**
  workflow_dispatch: {}

jobs:

  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        install-extras: [ "", "full-auth" ]
        python-version: [ "3.12" ]
    name: Python ${{ matrix.python-version }}${{ matrix.install-extras && ' ' || '' }}${{ matrix.install-extras }}
    runs-on: ubuntu-26.04
    timeout-minutes: 7  # usually 5 mins with coverage
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: astral-sh/setup-uv@v10.2.0
      - uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - run: uv sync --no-dev --group test
      - run: uv sync --no-dev --group test --extra ${{ matrix.install-extras }}
        if: ${{ matrix.install-extras }}
      - run: uv run --no-sync coverage run --branch --source=kopf -m pytest --color=yes --timeout=2

      - name: Publish coverage to Coveralls.io
        uses: coverallsapp/github-action@v2
        with:
          parallel: true
          flag-name: ${{ matrix.python-version }}${{ matrix.install-extras && ' ' || '' }}${{ matrix.install-extras }}
        if: success()
        continue-on-error: true  # tends to fail with no code changes (e.g. only CI/docs)
      - name: Publish coverage to CodeCov.io
        uses: codecov/codecov-action@v7
        env:
          PYTHON: ${{ matrix.python-version }}
        with:
          flags: unit
          env_vars: PYTHON
          token: ${{ secrets.CODECOV_TOKEN }}
        if: success()
